Name:           ros-indigo-alfred-bot
Version:        0.1.121
Release:        0%{?dist}
Summary:        ROS alfred_bot package

Group:          Development/Libraries
License:        GPLv3
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-rosjava-core
Requires:       ros-indigo-rosjava-dynamic-reconfigure
Requires:       ros-indigo-smarthome-comm-msgs
Requires:       ros-indigo-smarthome-common-driver
Requires:       ros-indigo-smarthome-media-model
Requires:       ros-indigo-smarthome-media-msgs
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-rosjava-build-tools
BuildRequires:  ros-indigo-rosjava-core
BuildRequires:  ros-indigo-rosjava-dynamic-reconfigure
BuildRequires:  ros-indigo-smarthome-comm-msgs
BuildRequires:  ros-indigo-smarthome-common-driver
BuildRequires:  ros-indigo-smarthome-media-model
BuildRequires:  ros-indigo-smarthome-media-msgs

%description
This package is bot of Alfred Assitant for ROS. This package is part of Alfred
Assistant stack.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sat Jun 11 2016 Mickael Gaillard <mick.gaillard@gmail.com> - 0.1.121-0
- Autogenerated by Bloom

